from lx_anonymizer.report_reader_settings import (
    DEFAULT_CUT_OFF_BELOW_LINE_FLAG as CUT_OFF_BELOW_LINE_FLAG,
    DEFAULT_ENDOSCOPE_INFO_LINE_FLAG as ENDOSCOPE_INFO_LINE_FLAG,
    DEFAULT_EXAMINER_INFO_LINE_FLAG as EXAMINER_INFO_LINE_FLAG,
    DEFAULT_FIRST_NAMES as FIRST_NAMES,
    DEFAULT_LAST_NAMES as LAST_NAMES,
    DEFAULT_PATIENT_INFO_LINE_FLAG as PATIENT_INFO_LINE_FLAG,
    DEFAULT_SETTINGS,
    default_report_reader_flags,
)

CUT_OFF_ABOVE_LINE_FLAGS = default_report_reader_flags().cut_off_above
CUT_OFF_BELOW_LINE_FLAGS = default_report_reader_flags().cut_off_below

__all__ = [
    "CUT_OFF_ABOVE_LINE_FLAGS",
    "CUT_OFF_BELOW_LINE_FLAG",
    "CUT_OFF_BELOW_LINE_FLAGS",
    "DEFAULT_SETTINGS",
    "ENDOSCOPE_INFO_LINE_FLAG",
    "EXAMINER_INFO_LINE_FLAG",
    "FIRST_NAMES",
    "LAST_NAMES",
    "PATIENT_INFO_LINE_FLAG",
]
