name: CI

on:
  push:
    branches: [main]
    tags:  # Optional: only publish on tagged releases
      - 'v*'  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # (Optional) run tests, lint, etc. in preceding steps

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build and twine
        run: |
          pip install --upgrade pip
          pip install build twine

      - name: Build Distribution
        run: |
          python -m build

      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          python -m twine upload dist/*
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
